name: expenses_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.3
  json_annotation: ^4.8.1
  auto_route: ^7.8.4
  flutter_hooks: ^0.20.4
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  very_good_analysis:
  build_runner: 
  json_serializable: ^6.7.1
  custom_lint:
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
